//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formData
    {
        public int SubmissionID { get; set; }
        public Nullable<int> formID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public Nullable<int> MobileNumber { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public string ReqStatus { get; set; }
    
        public virtual form form { get; set; }
        public virtual userid userid1 { get; set; }
    }
}
